### ISSUE TITLE
Mongorestore needs db name

### ISSUE THREAD

**Issue by davejtoews** [adamhenson/mongobackup#1]
Restoring a db using this repo and mongodb 3.2 results in a whole bunch of

```
don't know what to do with file "path/to/file.bson", skipping...
```

This is the same as if I had used

```
mongorestore path/to/dump
```

I believe that is old syntax and in the current version of mongodb you need to name the database you're restoring.

```
mongorestore -d databasename path/to/dump
```

**Comment by adamhenson** [comment]
Thanks @davejtoews. I haven't updated this in a very long time. I'd say it's due. Thanks for opening this. I'll have a fix shortly.

**Comment by davejtoews** [comment]
Glad to hear it. Thanks.

**Comment by adamhenson** [comment]
@davejtoews - I've done some testing. With versions of Mongo > 3.0 the `db` argument is needed in the [mongorestore](http://docs.mongodb.org/manual/reference/program/mongorestore/) command and therefore needs to be specified as an option in our `mongobackup.restore` method (assuming Gulp). This module actually supports that without any updates. I will however update the documentation. The database name isn't picked up from the `path` option (as it used to) - we need to additionally specify it in the `db` option. I will update the README momentarily but in the meantime here's the updated example using the `db` option. I'm not sure if you're using Grunt or Gulp, but either way please give this a shot (or something similar with Grunt) and let me know if you have any issues or you need me to clarify:

```
// mongorestore - restore 'testdb' database to localhost 
gulp.task('mongorestore', function() {
  mongobackup.restore({
    db : 'testdb',
    host : 'localhost',
    drop : true,
    path : './dumps/mongo/testdb'
  });
});
```

**Comment by davejtoews** [comment]
@adamhenson I thought I'd tried that, guess I didn't. It works. Thanks for updating the docs.

**Comment by adamhenson** [comment]
@davejtoews - So, essentially you were correct. But the code translates the option to something like this `--db`. Since `-d` is a one hyphen flag, we can't use that. So, please use `db` as an options.

Hope this works for you :)

**Comment by adamhenson** [comment]
@davejtoews - No prob, anytime! Thanks for contributing. This definitely needed to be changed. I had no idea.
